#source 'https://github.com/rasyidr298/MovieCataologuePodspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

use_frameworks!
workspace 'MovieCatalogue'

target 'MovieCatalogue' do
  pod 'Core', :git => 'https://github.com/rasyidr298/MovieCatalogueCore.git'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftLint'
  pod 'SDWebImageSwiftUI'
  pod 'RealmSwift'
end

target 'Common' do
  project '../Modules/Common/Common'
  pod 'SDWebImageSwiftUI'
end

target 'Movie' do
  pod 'Core', :git => 'https://github.com/rasyidr298/MovieCatalogueCore.git'
  project '../Modules/Movie/Movie'
  pod 'RealmSwift'
  pod 'Alamofire', '~> 5.2'
end

target 'Home' do
  project '../Modules/Home/Home'
  pod 'RealmSwift'
  pod 'SDWebImageSwiftUI'
end

target 'Detail' do
  project '../Modules/Detail/Detail'
  pod 'SDWebImageSwiftUI'
end

target 'Favorite' do
  project '../Modules/Favorite/Favorite'
  pod 'SDWebImageSwiftUI'
end

target 'SearchMovie' do
  project '../Modules/SearchMovie/SearchMovie'
  pod 'SDWebImageSwiftUI'
end

target 'Profile' do
  project '../Modules/Profile/Profile'
  pod 'RealmSwift'
end

 post_install do |pi|
     pi.pods_project.targets.each do |t|
       t.build_configurations.each do |config|
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
       end
     end
 end
